name: Check vCPU on BuildJett

on: push

jobs:
  check_cpu:
    runs-on: namespace-profile-default # Ganti dengan runner BuildJet yang ingin Anda cek

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Works
      run: |
        lscpu
        
